#app.yaml
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.py

libraries:
- name: flask
  version: .12

env_variables:
  DB_USER: flaskapp
  DB_PASS: cabbage
  DB_NAME: chevron
  CLOUD_SQL_CONNECTION_NAME: hackrice11:us-central1:mysqlchev
