#app.yaml
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: flask
  version: .12

env_variables:
  CLOUD_SQL_USERNAME: flaskapp
  CLOUD_SQL_PASSWORD: cabbage
  CLOUD_SQL_DATABASE_NAME: chevron
  CLOUD_SQL_CONNECTION_NAME: hackrice11:us-central1:mysqlchev
